[package]
name = "ascii-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.4"
image = "0.24.6"
term_size = "0.3.2"
unicode-width = "0.1.10"
